@echo off
echo ========================================
echo   SETUP NGROK CHO EXPLODING KITTENS
echo ========================================
echo.
echo Buoc 1: Chay server
echo   - Mo terminal moi va chay: start-server.bat
echo.
echo Buoc 2: Chay ngrok
echo   - Chay lenh: ngrok http 7777
echo.
echo Buoc 3: Copy URL ngrok
echo   - VD: https://abc123.ngrok-free.app
echo.
echo Buoc 4: Nhap URL ngrok vao day:
set /p NGROK_URL="Nhap URL ngrok (khong co https://): "
echo.
echo Dang cap nhat file .env...
echo # Auto-generated by setup-ngrok.bat > client\.env
echo VITE_SERVER_URL=https://%NGROK_URL%/ >> client\.env
echo.
echo ========================================
echo   HOAN THANH!
echo ========================================
echo.
echo File client/.env da duoc cap nhat:
echo VITE_SERVER_URL=https://%NGROK_URL%/
echo.
echo Bay gio chay: start-client.bat
echo.
pause
